require:
  - rubocop-ast
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-factory_bot

Layout/LineLength:
  Enabled: false

AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Enabled: true
  Exclude:
    - "db/**/*"
